# 개발 환경 특화 설정
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    volumes:
      - ./packages/api:/app
      - ./packages/shared:/app/packages/shared
      - api-node-modules:/app/node_modules
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
      - CORS_ORIGINS=["http://localhost:3000", "http://dev.car-goro.local"]
      - API_DOMAIN=api.car-goro.local
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./packages/shared:/app/packages/shared
      - frontend-node-modules:/app/packages/frontend/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maintenance_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development

  redis:
    ports:
      - "6379:6379"

volumes:
  api-node-modules:
  frontend-node-modules: