"""변경 내용 설명

Revision ID: 9644399ba93c
Revises: 00276e7bfadf
Create Date: 2025-04-11 16:21:07.223070

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9644399ba93c"
down_revision = "00276e7bfadf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
