"""Update model inheritance and relationships

Revision ID: 980e6594b9b3
Revises: 9644399ba93c
Create Date: 2025-04-11 17:01:54.543411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980e6594b9b3'
down_revision = '9644399ba93c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shop_images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('shop_services', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('shop_services', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('technicians', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('technicians', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicians', 'updated_at')
    op.drop_column('technicians', 'created_at')
    op.drop_column('shop_services', 'updated_at')
    op.drop_column('shop_services', 'created_at')
    op.drop_column('shop_images', 'updated_at')
    op.drop_table('todos')
    # ### end Alembic commands ### 